Issue 1 common api account
mikhailsnnt/financial_assistant pull request #20
Opened 2022-12-11 18:03 UTC by DmitriIvanov6

User account microservice added

2022-12-14 14:58 UTC, mikhailsnnt requested changes

2022-12-14 14:58 UTC, mikhailsnnt commented on common-api-account/src/main/java/ru/gb/config/SecurityConfig.java
> +    String publicKey;
Можешь пожалуйста избавиться от хранения publicKey. Мы ведь используем его только для создания JwtRsaParser.

2022-12-14 14:58 UTC, mikhailsnnt commented on common-api-account/src/main/java/ru/gb/entities/UserAccount.java
> +@Data
Вот это еще отмечаю

2022-12-14 14:58 UTC, mikhailsnnt commented on common-api-account/src/main/java/ru/gb/exceptions/FOException.java
> +public class FOException extends Exception {
Для ошибок сделали отдельную либу, закинь их туда пожалуйста. И от ControllerAdvic'а можно избавиться, накинув а ошибки аннотацию @ResponseStatus

2022-12-14 14:58 UTC, mikhailsnnt commented on sql/flyway/common-api-account/V1_init_DB.sql
> +                                     name varchar(250),
Папка указывает не на названи е сервиса, а на название дб. Поменяй пожалуйста

2022-12-14 14:58 UTC, mikhailsnnt commented on common-api-account/src/main/java/ru/gb/servicies/UserAccountServiceImpl.java
> +import javax.transaction.Transactional;
Здесь транзакции не нужны, все операции атомарны

2022-12-14 14:58 UTC, mikhailsnnt commented on common-api-account/pom.xml
> +        </dependency>
Можешь подключиться к  Eureke пожалуйста.

org.springframework.cloud:spring-cloud-starter-netflix-eureka-client
Возможно понадобиться
org.springframework.cloud:spring-cloud-starter-netflix-hystrix
и анотация 
@EnableEurekaClient

2022-12-19 19:30 UTC, DmitriIvanov6 commented on common-api-account/src/main/java/ru/gb/servicies/UserAccountServiceImpl.java
> +import javax.transaction.Transactional;
исправил

2022-12-19 19:30 UTC, DmitriIvanov6 commented on sql/flyway/common-api-account/V1_init_DB.sql
> +                                     name varchar(250),
исправил

2022-12-19 19:30 UTC, DmitriIvanov6 commented on common-api-account/src/main/java/ru/gb/exceptions/FOException.java
> +public class FOException extends Exception {
сделал

2022-12-19 19:30 UTC, DmitriIvanov6 commented on common-api-account/src/main/java/ru/gb/entities/UserAccount.java
> +@Data
исправил

2022-12-19 19:31 UTC, DmitriIvanov6 commented on common-api-account/src/main/java/ru/gb/config/SecurityConfig.java
> +    String publicKey;
исправил

2022-12-20 16:12 UTC, merged